### ISSUE TITLE
3.2.10 - 3.2.15

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim11#11]
Ne uklapaju se u ono što smo pričali. Za radnike se unose osnovni podaci. Svaki radnik pripada nekoj firmi. Za svaku firmu se posebno pravi obračun po mjesecima. Dakle obračun za januar, obračun za februar. Svaki od tih obračuna ima ulazne podatke za svakog radnika. Najčešće je to samo stvarni rad u punom iznosu sati koji je definisan za taj mjesec. Dakle jedan radnik može imati 0 sati bolovanja u januaru, 16 sati u februaru, itd. Stvari rad može biti 176 radnih sati u januaru, 160 u februaru, itd. Svi ti parametri se unesu za svaki mjesec i za svakog radnika i na osnovu njih se pravi obračun. Vi ovdje nemate uopšte pojam mjeseca za koji se obračunava.

**Comment by ensarmuratovic** [comment]
Gdje mozemo naci informacije kako se izračunava plata za bolovanje i godišnji odmor, tj koliki je procenat smanjenja plate u odnosu na platu za puno radno vrijeme?

**Comment by deancupovic** [comment]
Pričali smo u interview o tome. godišnji odmor je 100%, bolovanje je 80%.
