### ISSUE TITLE
Promjena ličnih podataka admin panel

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#24]
Komponenta: 
Admin panel - prikaz ličnih podataka

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Lični podaci na administratorskom panelu se ne mogu mijenjati, iako je dizajnom interfejsa to predloženo

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Moj račun" u donjem lijevom dijelu prikazanog prozora

Slika dobijenog prozora:
![2l](https://cloud.githubusercontent.com/assets/9987650/7838498/85ac10c2-048d-11e5-9fb8-2561fa3b2561.png)
Slika očekivanog prozora:
![2d](https://cloud.githubusercontent.com/assets/9987650/7838511/915fbd2e-048d-11e5-805a-3fe6c836472e.png)

**Comment by zloco** [comment]
rijeseno
