### ISSUE TITLE
Pretraga firmi

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#25]
Komponenta: 
Admin panel - ažuriranje firmi

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri unosu specifičnih testnih podataka, opisanih u koracima izazivanja problema, pretraga firmi ne funkcioniše korektno

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodaj"
6. Unijeti "prvaFirma" u polje "Naziv", te "prvoSjedište" u polje "Sjedište"
7. Kliknuti na dugme "Potvrdi"
8. Kliknuti na dugme "Dodaj"
9. Unijeti "prvaFirm" u polje "Naziv", te "prvoSjedište" u polje "Sjedište"
10. Unijeti slovo "p" polje za pretragu koje se nalazi u gornjem dijelu prozora

Slika dobijenog prozora:
![6l](https://cloud.githubusercontent.com/assets/9987650/7838980/37180eea-0490-11e5-8240-a5a5a2e61efd.png)

Slika očekivanog prozora nije moguća zbog nefunkcionalnosti same pretrage. Razlika u odnosu na dobijeni prozor bi bila ta da nema navedene firme "Temp" sa ID-em "1".

**Comment by ensarmuratovic** [comment]
Igrom slucaja si  ukucao "p" slovo u pretragu koje sadrze sve tri firme, a zbog mogucih naziva firmi koji mogu sadrzavati vise rijeci, mi smo pretragu zasnovali na "contains" funkciji koja provjerava da li naziv firme sadrzi uneseni slovo,slog ili rijec.
