### ISSUE TITLE
"Gubljenje" podataka o administratoru

### ISSUE THREAD

**Issue by mklisura1** [SoftverInzenjeringETFSA/SI2014Tim11#26]
Komponenta: 
Admin panel - prikaz ličnih podataka

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Lični podaci na administratorskom panelu nestaju

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u gornjem desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Izlaz" da bi se vratili na prethodni prozor

Slika dobijenog prozora:
http://prntscr.com/7a033l

Slika nakon što se vratimo na prozor "Početna"
http://prntscr.com/7a03e1

http://prntscr.com/7a03i5

Očekivani rezultat:

Prikaz podataka o administratoru

**Comment by mklisura1** [comment]
Isto je ako se prijavimo i sa drugim administratorskim profilom

**Comment by zloco** [comment]
rijeseno je sad sa svim buttonima, tj koji god da kliknes button na pocetnoj formi administratora, kad kliknes izlaz, prikazat ce ti dobrodosli, Admin
