### ISSUE TITLE
Validacija unosa firmi

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#27]
Komponenta: 
Admin panel - dodavanje firmi

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri dodavanju firmi, unos i potvrda nevalidnih podataka ne izaziva prikaz nikakve greške, ali se podaci ipak ne unesu u bazu, što korisnik ne zna

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodaj"
6. Ostaviti prazna sva polja i kliknuti "Potvrdi"

Dobijeni ekran:
![3l](https://cloud.githubusercontent.com/assets/9987650/7839316/15ff5d38-0492-11e5-9c41-b4f18151a855.png)

Očekivani rezultat: Bilo kakva forma obavijesti da podaci nisu validni, te da ih treba mijenjati. Korisnik ne zna da li su podaci uneseni ili ne.

**Comment by Irma12** [comment]
Popravljeno
