### ISSUE TITLE
Poruka pri dodavanju firmi

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#28]
Komponenta: 
Admin panel - dodavanje firmi

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri dodavanju firmi, unos i potvrda validnih podataka izaziva prikaz poruke "Uspješno ste izmjenili firmu"

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodaj"
6. Unijeti podatke "asd" u polje "Naziv", i "asd" u polje "Sjedište"
7. Kliknuti na dugme "Potvrdi" 

Dobijeni ekran:

![18l](https://cloud.githubusercontent.com/assets/9987650/7839468/c230b908-0492-11e5-92f6-d6b54fb5fad6.png)

Očekivani rezultat: Poruka "Uspješno ste dodali firmu", obzirom da se radi o dodavanju a ne o promjeni.

Treba naglasiti da se ovaj problem dešava u 80% slučajeva kada se navedeni koraci sprovedu. U ostalih 20% ili se prikaže ispravna poruka ili se ne prikaže ništa, ali se unos u bazu pravilno izvede.

**Comment by zloco** [comment]
rijeseno
