### ISSUE TITLE
Dodavanje iste firme

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#29]
Komponenta: 
Admin panel - dodavanje firmi

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri dodavanju firmi, moguće je dodati firmu sa istim nazivom i sjedištem. Postavlja se pitanje smisla pretrage po imenu.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodaj"
6. Unijeti podatke "asd" u polje "Naziv", i "asd" u polje "Sjedište"
7. Kliknuti na dugme "Potvrdi".
8. Kliknuti na dugme "Ok" na prozoru koji iskoči.
9. Kliknuti na "Dodaj"
10. Unijeti podatke "asd" u polje "Naziv", i "asd" u polje "Sjedište"
11. Kliknuti na dugme "Potvrdi".
12. Kliknuti na dugme "Ok" na prozoru koji iskoči.

Dobijeni ekran:

![17l](https://cloud.githubusercontent.com/assets/9987650/7839617/9d597b32-0493-11e5-8bc7-54351f136a8b.png)

Očekivani rezultat: Neka vrsta poruke da je nemoguće dodati firmu sa istim imenom i sjedištem. Ukoliko je u rješenju zamišljeno da se može dodati firma sa istim imenom i sjedištem, onda pretraga po imenu gubi smisao. U tom slučaju treba omogućiti pretragu po nekom drugom unikatnom i praktičnom atributu.

**Comment by Irma12** [comment]
Rijeseno
