### ISSUE TITLE
Poruka pri dodavanju uposlenika

### ISSUE THREAD

**Issue by mklisura1** [SoftverInzenjeringETFSA/SI2014Tim11#30]
Komponenta: 
Admin panel - dodavanje firmi

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri dodavanju uposlenika ne dobije ne nikakva poruka ni o uspješnosti dodavanja ni o neuspješnosti. Ne upiše se ništa u bazu.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "operater" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Korisnički računi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodavanje"
6. Unijeti podatke kao na slici:
http://prntscr.com/7a0e7c
7. Kliknuti na dugme "Potvrdi"

Dobijeni ekran:

http://prntscr.com/7a0e7c

Očekivani rezultat: Poruka "Uspješno ste dodali uposlenika" ili poruka "Neuspješno dodavanje uposlenika" ili bilo kakva greška o unosu.

**Comment by zloco** [comment]
kad uneses jmbg ispise Uspjesno ste dodali korisnika, za neuspjesno dodavanje ne ispise nista, samo ne prodje zahtjev

**Comment by zloco** [comment]
sad ispisuje i za neuspjesno dodavanje, tj ispise sta nije dobro uneseno
