### ISSUE TITLE
Ažuriranje uposlenika

### ISSUE THREAD

**Issue by mklisura1** [SoftverInzenjeringETFSA/SI2014Tim11#31]
Komponenta: 
Operater panel - ažuriranje uposlenika

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri ažuriranju uposlenika ne dobije se nikakva poruka ni o uspješnosti ažuriranja ni o neuspješnosti. Ne izvrši se izmjena podataka

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "operater" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Korisnički računi" u desnom dijelu prikazanog prozora
5. Odabrati nekog uposlenika i kliknuti da dugme "Ažuriranje"
6. Izmjeniti podatke 
7. Kliknuti na dugme "Potvrdi"

Dobijeni ekran:

http://prntscr.com/7a0gdt

Očekivani rezultat: Poruka "Uspješno ste izmjenili uposlenika" ili poruka "Neuspješna izmjena uposlenika" ili bilo kakva greška o unosu.

**Comment by zloco** [comment]
sad ispisuje :D
