### ISSUE TITLE
Unos firme sa nevalidnim datumom

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#32]
Komponenta: 
Admin panel - dodavanje firmi

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri dodavanju firmi, moguće je dodati firmu sa datumom dodavanja koji još nije nastupio.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodaj"
6. Unijeti podatke "asd" u polje "Naziv", i "asd" u polje "Sjedište".
7. Kliknuti na ikonicu pored polja za datum, te odabrati datum koji još nije nastupio.
8. Kliknuti na dugme "Potvrdi".
9. Kliknuti na dugme "Ok" na prozoru koji iskoči.

Dobijeni ekran:

![4l](https://cloud.githubusercontent.com/assets/9987650/7839893/1b4bcdd2-0495-11e5-82b0-89b36a271ac0.png)

Očekivani rezultat: Obavještenje da nije moguće za datum dodavanja odabrati datum koji još nije nastupio.

**Comment by Irma12** [comment]
Popravljeno
