### ISSUE TITLE
Podaci na formi za ažuriranje operatera nisu prikazani

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#33]
Komponenta: 
Admin panel - ažuriranje operatera

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Pri ažuriranju operatera, ne prikažu se podaci koji se trebaju ažurirati

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje operatera" u desnom dijelu prikazanog prozora
5. Kliknuti na prvi red tabele
6. Kliknuti na dugme "Ažuriranje"

Dobijeni ekran:

![12l](https://cloud.githubusercontent.com/assets/9987650/7839986/9ec97d94-0495-11e5-8ef2-fa8a6df64f0e.png)

Očekivani rezultat: Podaci od odabranog operatera se prikažu, da bi se mogli mijenjati.

**Comment by zloco** [comment]
rijeseno
