### ISSUE TITLE
Prikaz svih operatera bez obzira na odabranu firmu

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#34]
Komponenta: 
Admin panel - ažuriranje operatera

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Na formi za pregled operatera, odabirom bilo koje firme ispisuje se čitava lista operatera.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje operatera" u desnom dijelu prikazanog prozora
5. Odabrati na padajućoj listi firmi neki drugu firmu od trenutno odabrane.

Dobijeni ekran:

![14l](https://cloud.githubusercontent.com/assets/9987650/7840101/0d1bf948-0496-11e5-8dfd-d3bc14f40e0a.png)

Očekivani rezultat: Lista prikazanih operatera se ažurira sa onim operaterima koji su u odabranoj firmi.

**Comment by ensarmuratovic** [comment]
Ovo sad radi :D
