### ISSUE TITLE
Pretraga na raspodjeli operatera ne funkcioniše

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#35]
Komponenta: 
Admin panel - raspodjela operatera

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Na formi za raspodjelu operatera, unosom validnog ID-a i odabirom validne firme aplikacije počinje da zastajkuje i ne prikaže traženog operatera.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Raspodjela operatera" u desnom dijelu prikazanog prozora
5. Unijeti "2" u polje "ID", i odabrati "1 Temp" u polju "Firma".

Dobijeni ekran:
![15l](https://cloud.githubusercontent.com/assets/9987650/7840270/dedd2164-0496-11e5-9343-758d056c5f92.png)

Prikaz unosa u bazi kao potvrda da operater postoji:
-Tabela operater:
![15la](https://cloud.githubusercontent.com/assets/9987650/7840348/4713767a-0497-11e5-9c87-5fdbd2ce1a66.png)

-Tabela osoba:
![15lb](https://cloud.githubusercontent.com/assets/9987650/7840357/52855a82-0497-11e5-98ac-4c4f41fa7b6a.png)

Očekivani rezultat: Lista prikazanih operatera se ažurira sa onim operaterima koji odgovaraju unesenim podacima. U ovom slučaju to bi bio operater "Temp Tempi?" sa ID-em "2".

**Comment by zloco** [comment]
raspodjela operatera obrisana jer nema nikakvu funkciju (radi potpuno isto kao azuriranje operatera)
