### ISSUE TITLE
Dodavanje permisija gasi formu

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#36]
Komponenta: 
Admin panel - ažuriranje operatera

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Na formi za ažuriranje operatera, klikom na "Dodaj permisije" forma se gasi, ali aplikacija kao proces ne terminira.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje operatera" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme "Dodaj permisije"

Prikaz ekrana prije koraka 5:
![11la](https://cloud.githubusercontent.com/assets/9987650/7840593/6d205972-0498-11e5-831e-81afc3ba5ce5.png)

Prikaz ekrana nakon koraka 5:
![11lb](https://cloud.githubusercontent.com/assets/9987650/7840596/702037dc-0498-11e5-89c7-d1fbeded4bde.png)

Očekivani rezultat: Prikaz forme za dodavanje permisija.

**Comment by zloco** [comment]
rijeseno
