### ISSUE TITLE
Nekorektan prikaz operatera pri otvaranju forme

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#37]
Komponenta: 
Admin panel - ažuriranje operatera

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Na formi za ažuriranje operatera, pri samom otvaranju forme nisu prikazani svi operateri koji trebaju biti prikazani. Tek nakon unosa bilo čega u polje "ID", te brisanje unesene vrijednosti, prikažu se potrebni operateri.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje operatera" u desnom dijelu prikazanog prozora
5. Unijeti "1" u polje "ID" i obrisati unesenu vrijednost, tako da je polje "ID" prazno.

Prikaz ekrana prije koraka 5:
![10l](https://cloud.githubusercontent.com/assets/9987650/7840775/450e817e-0499-11e5-8865-f47ad79bdac1.png)

Prikaz ekrana nakon koraka 5:
![10la](https://cloud.githubusercontent.com/assets/9987650/7840777/483b735c-0499-11e5-924d-78c53c75dab8.png)

Očekivani rezultat: Prikaz svih operatera poslije koraka 4.

**Comment by zloco** [comment]
rijeseno
