### ISSUE TITLE
"Zaostali" podaci na formi za dodavanje firme

### ISSUE THREAD

**Issue by zlatancilic** [SoftverInzenjeringETFSA/SI2014Tim11#38]
Komponenta: 
Admin panel - dodavanje firme

commit ID: 
ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Na formi za ažuriranje firmi, nakon dodavanja jedne firme, potvrde dodavanja, te ponovno otvaranja forme za dodavanje, podaci od prošlog dodavanja su još uvijek tu.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na "Dodaj".
6. Unijeti "asd" u polje "Naziv" i "asd" u polje "Sjedište".
7. Kliknuti na "Potvrdi".
8. Kliknuti na "OK" na iskačućem prozoru.
9. Kliknuti opet na "Dodaj"

Prikaz dobijenog ekrana:
![5l](https://cloud.githubusercontent.com/assets/9987650/7841064/8c6e98dc-049a-11e5-8ab0-31dc493729af.png)

Očekivani rezultat: 
![5d](https://cloud.githubusercontent.com/assets/9987650/7841065/908f4718-049a-11e5-9d01-dcbb4defaa68.png)

**Comment by Irma12** [comment]
Popravljeno...
