### ISSUE TITLE
Raspodjela operatera

### ISSUE THREAD

**Issue by mklisura1** [SoftverInzenjeringETFSA/SI2014Tim11#39]
Komponenta: 
Admin panel - ažuriranje operatera

commit ID: ae925b67bb5ac4c9c15df3136436a55e06c5602d

Opis problema: Na formi za raspodjelu operatera, pri samom otvaranju forme nisu prikazani svi operateri koji trebaju biti prikazani.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Raspodjela  operatera" u desnom dijelu prikazanog prozora

Očekivani rezultat: Prikaz svih operatera poslije koraka 4 radi dalje raspodjele operatera.

**Comment by zloco** [comment]
raspodjela operatera obrisana jer nema nikakvu funkciju (radi potpuno isto kao azuriranje operatera)
