### ISSUE TITLE
Brisanje firmi

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#40]
Komponenta: 
Admin panel - brisanje firmi

commit ID: ae925b6

Opis problema: Na formi "Prikaz firmi" prilikom klika na Brisanje se pojavi dijalog za potvrdu brisanja bez obzira na to što nije odabrana nijedna firma.

http://pokit.org/get/?3c60935594b520fb6ac91471b9896080.jpg

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje firmi" u desnom dijelu prikazanog prozora
5. Kliknuti na dugme brisanje

Očekivani rezultat: Poruka o tome da nije selektovana firma za brisanje.

**Comment by zloco** [comment]
rijeseno
