### ISSUE TITLE
Interface za dodavanje firmi ne odgovara SRS-u

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#41]
Komponenta:
GUI: AdministratorPocetna.java

commit ID:
d28ee68e5aa7d1a9369f90dc1142aa929ec3f000

Opis problema:
Kod dodavanja nove firme, prema SRS-u očekuju se sljedeći ulazi:
- Naziv firme  
- ID firme  
- Ime i prezime administratora koji je zadužen za firmu  
- Vrsta firme  
- Datum dodavanja firme   

Međutim, na formi za dodavanje su ponuđena sljedeća polja:
- Naziv 
- Sjediste
- Administrator
- Datum dodavanja

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
http://imgur.com/iJd7U0P
5. Kliknuti na dugme Ažuriranje firmi
6. Kliknuti na dugme Dodaj
http://imgur.com/xwUB7Bo

**Comment by zloco** [comment]
ID firme se ne moze/ne treba dodavati zbog baze koja sama generise ID, a vrsta firme nema logike pa smo izbrisali

**Comment by SumejjaPorca** [comment]
(Y)

**Comment by SumejjaPorca** [comment]
Mislim da bi onda ovo trebala staviti kao rijesen issue, a ne wontfix, jer si ga ispravila, a ovak oce ti mozda bodovi otici na ovo :/

**Comment by Irma12** [comment]
ja sam stavila wontfix a koliko se sjecam dean je rekao da to radimo u slucajevima ovakvim, kad se ne slaze a ne zelimo npr koristiti taj dizajn iz uisa:/
