### ISSUE TITLE
Interface za dodavanje operatera ne odgovara SRS-u

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#45]
Komponenta: Dodavanje novog operatera - Admin panel

commit ID:
d28ee68

Opis problema:
Kod dodavanja novog operatera, prema SRS-u očekuju se sljedeći ulazi:
- Ime  
- Prezime  
- JMBG  
- Adresa  
- Kontakt telefon  
- Datum zapošljavanja  
- Korisničko ime  
- Firma kojoj se dodjeljuje

Međutim, na formi za dodavanje su ponuđena sljedeća polja:
- Ime
- Prezime
- JMBG
- Adresa
- Pozicija u firmi
- Zaposlen

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
http://imgur.com/iJd7U0P
5. Kliknuti na dugme Ažuriranje operatera
6. Kliknuti na dugme Dodavanje

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/GjbfJKb

**Comment by zloco** [comment]
dodani telefon i korisnicko ime, a firma se prosljedjuje iz prethodne forme, s toga nije potrebno unositi na ovoj formi

**Comment by SumejjaPorca** [comment]
(Y)
