### ISSUE TITLE
Upitno dodavanje operatera - nema potvrde o uspjesnom zahtjevu

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#46]
Komponenta: Dodavanje novog operatera - Admin panel

commit ID:
d28ee68

Opis problema:
Nakon dodavanja novog operatera, prema SRS-u očekuju se potvrda o uspješnom dodavanju, međutim nakon popunjavanja svih polja i pritiskom na Potvrdi, ništa se ne dešava. Kasnije kada provjerite, na prikazu operatera novi operater nije prikazan.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
http://imgur.com/iJd7U0P
5. Kliknuti na dugme Ažuriranje operatera
6. Kliknuti na dugme Dodavanje
7. Popuniti polja sa validnim podacima po SRS-u
8. Kliknuti na dugme Potvrdi

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/xfnKsEr

Očekivani izlaz:
Potvrda o uspješnom ili neuspješnom dodavanju novog operatera.

Dobijeni rezultat:
Ništa se ne desi.

**Comment by zloco** [comment]
rijeseno
