### ISSUE TITLE
Los princip izmjene firme

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#48]
Komponenta:
GUI: DodavanjeEditovanjeFirmi.java

commit ID:
d28ee68

Opis problema:

Kada se odabere firma za editovanje, na formi koja se pojavi  pise Dodavanje firme, što može biti zbunjujuće za osobu koja radi na aplikaciji. Pored toga, uneseni podaci o firmi se ne popune automatski na odgovarajuća mjesta, te je izmjena otežana.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
http://imgur.com/iJd7U0P
5. Kliknuti na dugme Ažuriranje firmi
6.Odabrati firmu
7. Kliknuti na dugme Uredi

**Comment by Irma12** [comment]
Ispravljena je poruka, podaci nigdje nisu navedeni da ce se prikazivati prilikom editovanja ali pokusacemo i to dodati
