### ISSUE TITLE
Omogućeno nekorektno dodavanje firmi

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#49]
Komponenta:
GUI: AdministratorPocetna.java

commit ID:
d28ee68

Opis problema:

Dodavanje firmi nije usaglašeno sa SRS-om. U SRS-u stoji da je jedan od uslova validnosti unosa firme   da sva polja prilikom unosa moraju biti popunjena, no unos je uspješan ako se polje Administrator ostavi prazno.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
5. Kliknuti na dugme Ažuriranje firmi
6. Kliknuti na dugme Dodaj
7. Unijeti podatke u sva polja osim Administrator
8. Kliknuti na dugme potvrdi

**Comment by Irma12** [comment]
Rijeseno
