### ISSUE TITLE
Aplikacija se krahira prilikom unosa imena firme

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#50]
Komponenta:
GUI: AdministratorPocetna.java

commit ID:
d28ee68

Opis problema:

Aplikacija se krahira kada se kod unosa imena firme unesu slova tipa Č.Ć.Š, iako nigdje prilikom unosa nije spomenuto da su ta slova zabranjena.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
5. Kliknuti na dugme Ažuriranje firmi
6. Kliknuti na dugme Dodaj
7. Unijeti ime firme Voćko, Povrćko i sl.
8. Kliknuti na dugme Potvrdi

**Comment by Irma12** [comment]
Rijeseno, problem sa regexom..
