### ISSUE TITLE
Aplikacija se krahira prilikom klika na dugme Dodaj permisiju

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#51]
Komponenta: 
Admin panel - ažuriranje operatera

commit ID: d28ee68

Opis problema:

Aplikacija se krahira prilikom klika na dugme Dodaj permisiju ukoliko nije odabran nijedan operater.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
5. Kliknuti na dugme Ažuriranje operatera
6. Kliknuti na dugme Dodaj permisiju

**Comment by zloco** [comment]
zlaja je ovo vec postavio, a i rijeseno je u medjuvremenu
