### ISSUE TITLE
Naziv baze nije po specifikacijama

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#52]
Komponenta: Hibernate konfiguracija

commit ID:
d28ee68

Opis problema:
Konfiguracija baze nije po specifikacijama - > ime baze bi trebalo biti tim11, a ustvari je tim11baza - malo je nezahvalno jer se ta greška ne primijeti baš odmah, u svakom slučaju je bolje da se to ispravi, a nije ni teško.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Napraviti mysql bazu po specifikacijama - sa nazivom tim11
4. Pokrenuti Login formu
5. Pokušati se logirati

**Comment by ensarmuratovic** [comment]
Ispravljeno.
