### ISSUE TITLE
U raspodjeli operatera ne prikažu se svi dodani operateri

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#53]
Komponenta:
GUI: Raspodjela operatera - Admin panel

commit ID:
d28ee68

Opis problema:
Nakon logiranja na sistem kao admin,  pritiska na  dugme za raspodjelu operatera - ne prikaže se nijedan dodani operater, a u prikazu operatera kod ažuriranja operatera se prikazuje jedan već postojeći. Klik na dugme "Pretraži" je onemogućeno.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
5. Kliknuti na dugme Raspodjela operatera
6. Select-ovati firmu Temp1 i ukucati ID 1

Dobijeni rezultat:

Na formi za prikaz operatera ne postoji nijedan operater i ne može se kliknuti na dugme "Pretraži" - kao što se može vidjeti na slikama(linkovi ispod).
http://imgur.com/17UaFv4
http://imgur.com/JNqGXSh

Očekuje se da se prikaz operatera iz firme Temp1.

**Comment by zloco** [comment]
raspodjela operatera obrisana jer nema nikakvu funkciju (radi potpuno isto kao azuriranje operatera)

**Comment by SumejjaPorca** [comment]
Slažem se, super
