### ISSUE TITLE
Pogrešan prikaz operatera - u odnosu na bazu

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#54]
Komponenta:
GUI: Raspodjela operatera - Admin panel

commit ID:
d28ee68

Opis problema:
Nakon logiranja na sistem kao admin, pritiska na dugme za raspodjelu operatera ili ažuriranje operatera - ne prikaže se nijedan dodani operater koji se nalazi u bazi.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "admin" sa šifrom "pass"
5. Kliknuti na dugme Raspodjela operatera ili ažuriranje operatera

Dobijeni rezultat:

Na formi za prikaz operatera ne postoji nijedan operater od onih koji se nalaze u bazi - kao što se može vidjeti na slikama(linkovi ispod).
http://imgur.com/tVTLs53

Očekuje se prikaz operatera kao u sadržaju baze - 2 operatera sa id-em firme 1(A to je firma Temp1).

**Comment by zloco** [comment]
rijeseno
