### ISSUE TITLE
Upitna izmjena obračuna - nema poruke o potvrdi

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#55]
Komponenta:
GUI: Izmjena obračuna - Operater panel

commit ID:
d28ee68

Opis problema:
Nakon logiranja na sistem kao operater, pritiska na dugme za Obračun i popunjavanja polja za unos potrebnih podataka sa validnim podacima, i pritiska na dugme Potvrdi, ne dobije se nikakva poruka o procesiranju mog zahtjeva - loša praksa jer zbunjuje korisnika - on ne zna kako je završio njegov upit. 

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Obračun
6. Popuniti formu podacima koji se traže
7. Kliknuti na dugme Potvrdi

Dobijeni rezultat:

Nema poruke o uspješnoj ili neuspješnoj promjeni obračuna, kao što se može vidjeti na slici(link ispod).
http://imgur.com/a6z2eAF

Očekuje se potvrda o uspješno ili neuspješno izvršenom zahtjevu.

**Comment by zloco** [comment]
dodana poruka

**Comment by SumejjaPorca** [comment]
(Y)
