### ISSUE TITLE
Moguće dodati besmislene podatke u izmjenu obračuna

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#56]
Komponenta:
GUI: Obračun - Operater panel

commit ID:
d28ee68

Opis problema:
Nakon logiranja na sistem kao operater, pritiska na dugme za Obračun i unosa podataka koji su nelogični, neispravni, nakon pritiska na dugme "Potvrdi", ne desi se greška, barem se korisnik ne obavijesti o tome, tako da izgleda kao da se takvi podaci mogu slobodno unijeti.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Obračun
6. Popuniti podatke koji su neispravni
7. Kliknuti na dugme Potvrdi

Dobijeni rezultat:

Ništa se ne desi - kao što se može vidjeti na slikama(linkovi ispod).
http://imgur.com/KzYgAFi

Očekuje se da se prikaže poruka o greški.

**Comment by zloco** [comment]
pretpostavljam da ovo znaci da suma svih ostalih vrijednosti treba biti jednaka broju radnih dana?? ako jeste to, onda sam to sad rijesila, ako ne onda mi malo detaljnije napisi na sta si mislila :D

**Comment by SumejjaPorca** [comment]
Jeste to, i još za mjesec Februar npr. da ne može biti 31 dan

**Comment by zloco** [comment]
i to sam ispravila
