### ISSUE TITLE
Neto plata veća od bruto plate?

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#57]
Komponenta:
GUI: Prikaz obračuna - Operater panel

commit ID:
d28ee68

Opis problema:
Nakon logiranja na sistem kao operater, pritiska na dugme za Obračun i na dugme za Prikaz obračuna, podaci koji se prikažu su konfuzni - neto plata je veća od bruto plate, što ne bi trebalo biti, jer je neto plata = bruto_plata - porezi.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Obračun, selektovati zaposlenika Temp
6. Kliknuti na dugme Prikaz obračuna

Dobijeni rezultat:
http://imgur.com/g7bIaHu

Očekuju se podaci drugačije prirode.

**Comment by zloco** [comment]
rijeseno
