### ISSUE TITLE
Otvaranje forme azuriraj operatera iako operater nije odabran

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#58]
Komponenta: Azuriranje operatera - Admin panel

commit ID:
d28ee68

Opis problema:
Kada se klikne na dugme Ažuriranje, otvori se forma za ažuriranje operatera, iako nijedan operater nije odabran

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Ažuriranje operatera" u desnom dijelu prikazanog prozora
5. Kliknuti na prvi red tabele
6. Kliknuti na dugme "Ažuriranje"

**Comment by zloco** [comment]
rijeseno
