### ISSUE TITLE
Bacanje izuzetaka prilikom unosa ID

### ISSUE THREAD

**Issue by AlminHalilovic** [SoftverInzenjeringETFSA/SI2014Tim11#59]
Komponenta: Raspodjela operatera - Admin panel

commit ID:
d28ee68

Opis problema:

Prilikom unosa vrijednosti u polje ID na formi raspodjela opretera se pojavljuju izuzeci, koji usporavaju rad aplikacije te sprječavaju prikaz ispravnih vrijednosti.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Projekat-Tim11-0.0.1-SNAPSHOT-jar-with-dependencies.jar".
2. Ukucati "admin" u polje "Korisničko ime", te "pass" u polje "Šifra"
3. Kliknuti na dugme "OK"
4. Kliknuti na dugme "Raspodjela operatera" u desnom dijelu prikazanog prozora
5. Ukucati neku vrijednost u polje ID, koja nije prisutna u bazi

**Comment by zloco** [comment]
https://github.com/SoftverInzenjeringETFSA/SI2014Tim11/issues/35

ovo je zlaja vec postavio

**Comment by AlminHalilovic** [comment]
Nisam vidio da je kolega to već stavio. Moja greška.
