### ISSUE TITLE
Nemoguće prikazati afrikate

### ISSUE THREAD

**Issue by DAhmic** [SoftverInzenjeringETFSA/SI2014Tim11#60]
Komponenta: PodaciOperatera.java

Commit ID: 8b8e1d063025fc30a613799587196964737468a4

Opis problema: Na interfejsu se ne prikazuju afrikati a ne čuvaju se ni u bazi podataka

Koraci za reproduciranje problema: 
1.  Otvoriti Eclipse
2.  Clone-ati projekat sa repozitorija na github-u 
3.  Prijaviti se kao operater (Korisničko ime: operater, Šifra: operater)
4.  Kliknuti na dugme „Moj račun“

Stanje u bazi:
![image](https://cloud.githubusercontent.com/assets/10135153/7888640/39f0c7aa-063a-11e5-82dc-863952b968c9.png)

Dobijeni ekran: 
![image](https://cloud.githubusercontent.com/assets/10135153/7888653/47bbacb0-063a-11e5-863c-6926f76c2031.png)

Očekivani rezultat: Prikaz ispravnog imena, prezimena, adrese i drugih podataka.

**Comment by zloco** [comment]
mislim da je to do baze, jer isti problem imam na wt-u, dakle nije nesto sto mi mozemo rijesiti?

**Comment by DAhmic** [comment]
može se prilikom kreiranja baze dodati collation: utf8_slovenian_ci i onda rade i naša slova, ali biste morali novu skriptu za bazu praviti

**Comment by zloco** [comment]
nisam vidjela da je kod nas swedish, evo uklonila sam invalid labelu, ali sam ostavila wontfix

**Comment by zloco** [comment]
dodana je nova baza (skripta) pa skini, sad sama generisi lokalno bazu tim11 i stavi collation slovenian, ovim je rijesen problem
