### ISSUE TITLE
Dodavanje uposlenika sa neispravnim/nemogućim datumom zaposlenja

### ISSUE THREAD

**Issue by DAhmic** [SoftverInzenjeringETFSA/SI2014Tim11#61]
Komponenta: PodaciUposlenika.java

Commit ID:  b964c75ea681bee792bab277eb26627d5057ba05

Opis problema: Moguće je dodati uposlenika sa neispravnim/nemogućim datumom zaposlenja

Koraci za reproduciranje problema: 
1.  Otvoriti Eclipse
2.  Clone-ati projekat sa repozitorija na github-u 
3.  Prijaviti se kao operater (Korisničko ime: operater, Šifra: operater)
4.  Kliknuti na dugme „Korisnički računi“
5.  Kliknuti na dugme „Dodavanje“
6.  Popuniti podatke o uposleniku i kad godinu zaposlenja unijeti npr. 19
7.     Kliknuti dugme "Potvrdi"

Dobijeni ekran: 

![image](https://cloud.githubusercontent.com/assets/10135153/7890210/ca8d355a-0644-11e5-92d9-405884d1bf15.png)

Stanje u bazi:

![image](https://cloud.githubusercontent.com/assets/10135153/7890206/c518221a-0644-11e5-9a41-663dabf3f48d.png)

Očekivani rezultat: Prikaz poruke o neispravnom datumu i nemogućnosti dodavanja uposlenika.

**Comment by zloco** [comment]
pa zato sto si napisala 19, on to tumaci kao fakat 19. godina, a ne 2019.
e vec za 2019. ne moze proci zahtjev, to je regulisano
