### ISSUE TITLE
Kreiranje izvještaja

### ISSUE THREAD

**Issue by DAhmic** [SoftverInzenjeringETFSA/SI2014Tim11#62]
Komponenta: Izvjestaji.java

Commit ID: b964c75ea681bee792bab277eb26627d5057ba05

Opis problema: 

Koraci za reproduciranje problema: 
1.  Otvoriti Eclipse
2.  Clone-ati projekat sa repozitorija na github-u 
3.  Prijaviti se kao operater (Korisničko ime: operater, Šifra: operater)
4.  Kliknuti dugme „Obračun“
5.  Odabrati nekog od ponuđenih zaposlenika
6.  Kliknuti dugme „Izmjena obračuna“
7.  Unijeti potrebne podatke za obračun plate
8.  Kliknuti dugme „Potvrdi“
9.  Ukoliko je sve ispravno javit će se poruka „Uspješno ste dodali platu“
10. Zatvoriti poruku i kliknuti dugme „Izlaz“
11. Ponovo kliknuti dugme „Izlaz“
12. Kliknuti dugme „Izvještaji“
13. Unijeti ID uposlenika za koga smo dodali platu
14. Kliknuti dugme „Kreiraj izvještaj“

Dobijeni ekran: 
![image](https://cloud.githubusercontent.com/assets/10135153/7891407/b06ea372-064c-11e5-8f7f-ff9f2d184569.png)

Plata je sačuvana u bazi:
![image](https://cloud.githubusercontent.com/assets/10135153/7891412/bbb4b7f8-064c-11e5-9d53-3d1aa50977ff.png)

Očekivani rezultat: Prikaz izvještaja

**Comment by zloco** [comment]
rijeseno
