### ISSUE TITLE
Nejasan ishod dodavanja novog radnika - nema potvrde

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#63]
Komponenta: Dodavanje novog radnika - Operater panel

commit ID:
d28ee68

Opis problema:
Nakon dodavanja novog radnika, prema SRS-u očekuju se potvrda o uspješnom dodavanju, međutim nakon popunjavanja svih polja i pritiskom na Potvrdi, ništa se ne dešava. Kasnije kada provjerite, radnik se zaista doda.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Ažuriranje radnika
6. Kliknuti na dugme Dodavanje
7. Popuniti polja sa podacima
8. Kliknuti na dugme Potvrdi

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/l0y1stj

Očekivani izlaz:
Potvrda o uspješnom ili neuspješnom dodavanju novog radnika.

Dobijeni rezultat:
Ništa se ne desi.

**Comment by zloco** [comment]
nesto nije uredu sa hibernateom, u kodu pise da ce se pojaviti messagebox, ali on se iz nekog razloga ne pojavi, ugl rijesit ce se to

**Comment by ensarmuratovic** [comment]
Sad radi normalno. :dancer:
