### ISSUE TITLE
U polje za poziciju se može unijeti bilo šta

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#64]
Komponenta: Dodavanje novog radnika - Operater panel

commit ID:
d28ee68

Opis problema:
Prilikom dodavanja novog radnika, možete polje za poziciju popuniti bilo kakvim tekstom, koje ne odgovara postojećim pozicijama.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Ažuriranje radnika
6. Kliknuti na dugme Dodavanje
7. Popuniti polja sa podacima
8. Kliknuti na dugme Potvrdi

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/l0y1stj

Očekivani izlaz:
Poeuka o neuspješnom dodavanju novog radnika.

Dobijeni rezultat:
Radnik se doda.
http://imgur.com/9C8lbP9

**Comment by zloco** [comment]
nigdje (ni u SRSu) nije navedeno da ce se ovdje ogranicavati na bilo sta, moze se unijeti bilo sta (direktor, sef, pomocnik direktora, sta vec) tako da cu ovo oznaciti kao invalid
