### ISSUE TITLE
Nejasna uloga textboxa 

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#65]
Komponenta: Prikaz radnika - Operater panel

commit ID:
d28ee68

Opis problema:
U prikazu radnika, kao i u ostalim sličnim formama, nalazi se polje za unos, pored kojeg piše ID i vjerovatno se odnosi na firmu, a  firma se prije tog selektuje preko svog imena - kako je ime svake firme unikatno, polje za ID je višak, a što je još gore mogao bi biti sukob između te dvije vrijednosti ukoliko ne bi odgovarale jedna drugoj.

Koraci za reproduciranje problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Ažuriranje radnika

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/l0y1stj

**Comment by zloco** [comment]
nije to ID firme vec ID radnika, izaberes firmu iz comboboxa i onda searchas preko ID radnika

**Comment by SumejjaPorca** [comment]
ok :)
