### ISSUE TITLE
Nečitljiv prikaz izvještaja

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#66]
Komponenta: Izvještaj radnički - Operater panel

commit ID:
d28ee68

Opis problema:
Prikaz izvještaja za plate radnika je nečitljiv, radi boljeg razumijevanja i user-experience-a trebalo bi makar proširiti formu toliko da se vide naslovi kolona.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Izvještaji
6. Ukucati u polje za ID id nekog postojećeg radnika u bazi

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/Q2aOZrF

**Comment by zloco** [comment]
ovo nije bug, nit je opisano u SRSu, dakle nije ni validno, a i imena kolona su ionako predugacke, tako da bi morala forma citav ekran zauzeti da bi se svaka kolona mogla procitati, kolone se mogu prosirivati kada se pokrene aplikacija, pa ako nekog zanima moze je rucno prosiriti

**Comment by SumejjaPorca** [comment]
Inače ne bih to prijavljivala, ali ima nekoliko kolona sa prva 3 slova ista, pa nije jasno sta je, ali ako se mogu prosiriti, ok, slazem se. :)
