### ISSUE TITLE
Izvještaj se ne može ponovo vidjeti

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#67]
Komponenta: Izvještaj radnički - Operater panel

commit ID:
d28ee68

Opis problema:
Za radnika sa ID-em 5 kojem je obračunata plata, nakon što se obračuna i klikne se na pravljenje izvještaja, izvještaj se zaista napravi. Međutim, kad izađemo i ponovo se vratimo na to, traži nam da unesemo platu ponovo, iako je prethodno već unesena jednom i postoji u prikazu obračuna.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Napraviti obračun plate za nekog radnika koji postoji u bazi
5. Kliknuti na dugme Izvještaji
6. Ukucati u polje za ID id nekog postojećeg radnika u bazi

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
Prvi put nam izbaci ono što je i očekivano, a to je: 
http://imgur.com/Q2aOZrF

Međutim, drugi put:
http://imgur.com/Ch2R3mn

**Comment by zloco** [comment]
@SumejjaPorca ne razumijem ove korake za prikaz problema? ne poklapaju se sa onim sto si navela kao opis problema, nigdje nisi navela kada izadjem i gdje kliknem, i gdje ponovo udjem, molim te malo jasnije definisi, jer ja ne znam naci ovo, tj. meni ne izbacuje gresku, pa ne znam jel pogresno pratim ovo tvoje uputstvo
