### ISSUE TITLE
Pogrešna uloga datuma u pravljenju izvještaja u odnosu na SRS

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#68]
Komponenta: Izvještaj radnički - Operater panel

commit ID:
d28ee68

Opis problema:
Na formi za pravljenje izvještaja iznad Datuma piše: Datum kreiranja izvještaja, a prema SRS-u to bi trebao biti datum za koji se pravi izvještaj.

Koraci za prikaz problema:
1. Otvoriti Eclipse
2. Clone-ati projekat sa repozitorija na github-u (navedeni commit)
2. Import-ovati Maven projekat sa lokacije na kojoj se nalazi projekat
3. Pokrenuti Login formu
4. Logirati se kao "operater" sa šifrom "pass"
5. Kliknuti na dugme Izvještaji

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
http://imgur.com/Ch2R3mn

**Comment by zloco** [comment]
rijeseno
