### ISSUE TITLE
Loša organizacija testnih klasa

### ISSUE THREAD

**Issue by SumejjaPorca** [SoftverInzenjeringETFSA/SI2014Tim11#69]
Komponenta: Testna klasa FirmaTest.java

commit ID:
d28ee68

Opis problema:
Testna klasa bi trebala da se odnosi na sve CRUD-ove nad klasom Firma, a ne nad svim klasama sa njenom ovisnošću. A i u samom komentaru piše da je testna klasa za konstruktore firme. Smatram da je Single Responsibility dobar pristup.

Na sljedećem linku možete vidjeti sliku koja prikazuje opisani problem:
![image](https://cloud.githubusercontent.com/assets/8721239/7895186/6afbda3e-067f-11e5-8a5f-d975d515d29f.png)

**Comment by Strojki** [comment]
![objasnjenje](https://cloud.githubusercontent.com/assets/11410413/7898790/52d0335a-070c-11e5-90e8-771686bf38bb.jpg)
zbog navedenog ovo cemo zanemariti.

**Comment by SumejjaPorca** [comment]
moze moze,  izvinjavam se  :/
