### ISSUE TITLE
Forma login se ne ne unhide-a

### ISSUE THREAD

**Issue by nihad92** [SoftverInzenjeringETFSA/SI2014Tim11#72]
komponenta 
LoginForma (mada se odnosi na sve forme)

commitid:
e3313c29e9ee4848fd074b944c64d36b77504d7f

primjer
1. pokrenuti aplikaciju
2. ulogovati se na aplikaciju
3. zatvoriti trenutnu formu klikom na x

ocekivano da se login pojavi

**Comment by ensarmuratovic** [comment]
Login se pojavljuje klikom na dugme "Izlaz", nigdje nije precizirano niti napisano da se ocekuje login nakon klika na X neke forme.
