### ISSUE TITLE
Dodaj Firmu

### ISSUE THREAD

**Issue by nihad92** [SoftverInzenjeringETFSA/SI2014Tim11#73]
Komponenta:
Dodavanje firme

commit ID:
e3313c29e9ee4848fd074b944c64d36b77504d7f

Opis problema:
Ne dodaje firmu vec menja postojecu

Koraci za reproduciranje problema:
1. ulogovati se kao administrator
2. odabrati opciju Azuriranje firmi
3. odabrati opciju dodaj firmu
4. unjeti podatke i kliknuti potvrdi
5. kliknuti izlaz

Dobijeni rezultat:
izmjenjenjen postojeca firma

Očekivani rezultat:

tabela treba sadrzavati novu fimu

**Comment by zloco** [comment]
rijeseno
