### ISSUE TITLE
Dodavanje operatera

### ISSUE THREAD

**Issue by nihad92** [SoftverInzenjeringETFSA/SI2014Tim11#74]
Komponenta:
Podaci o operateru

commit ID:
e3313c29e9ee4848fd074b944c64d36b77504d7f

Opis problema:
na klik dodavanja operatera program baca null pointer exception

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. ulogovati se administratorskim akauntom
3.  odabrati opciju azuriraj operatere
4 odabrati firmu
5. odabrati opciju dodaj operatera
6. popuniti podatke
7. kliknite potvrdi

Dobijeni rezultat u konzoli:
![dodavanje operatera](https://cloud.githubusercontent.com/assets/11067294/7899139/16636688-0718-11e5-84e2-07521c57f4bd.PNG)

koristeni podaci:
![podaci](https://cloud.githubusercontent.com/assets/11067294/7899141/26c0458c-0718-11e5-9310-60d6c92d232f.PNG)

ne ispisuje nikakvu poruku o gresci 

moguc problem je prethodno brisanje firme i narusen integritet u bazi

**Comment by zloco** [comment]
rijeseno
