### ISSUE TITLE
NE prikazuje poruku o gresci na Formi Dodaj firmu

### ISSUE THREAD

**Issue by nihad92** [SoftverInzenjeringETFSA/SI2014Tim11#75]
Komponenta:
Podaci o operateru

commit ID:
e3313c29e9ee4848fd074b944c64d36b77504d7f

Opis problema:
na klik dodavanja operatera program baca null pointer exception

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju 
2. ulogovati se administratorskim akauntom
3.  odabrati opciju azuriraj Firmu
4 odabrati opciju dodaj firmu
5. popuniti podatke kao na slici
6. kliknite potvrdi

koristeni podaci:
![validnost](https://cloud.githubusercontent.com/assets/11067294/7899165/3d36f0b2-0719-11e5-858b-c05b0610e4d6.PNG)

ne ispisuje nikakvu poruku o gresci 

ocekivano da ispise poruku o gresci ili potvrdu o uspjesnom spasavanju

**Comment by Irma12** [comment]
Nalov, opis problema i prilozena slika se ne slazu

**Comment by Irma12** [comment]
Rijesen je problem dodavanja firmi sa manje od 3 slova sada ispisuje poruku upozorenja
