### ISSUE TITLE
Neprakticna pretraga korisnika

### ISSUE THREAD

**Issue by nihad92** [SoftverInzenjeringETFSA/SI2014Tim11#76]
Komponenta:
Izvjestaji

commit ID:
e3313c2

Opis problema:
Ne dodaje firmu vec menja postojecu

Koraci za reproduciranje problema:
1. ulogovati se kao operater sa privilegijama
2. odabrati opciju Izvestaji

Preveliko opterecenje memorije korisnika koji mora pamtiti id svakog uposlenika da bi moga izvrsiti pretragu i eventualno vidjeti izvestaj puno bolje resenje bi bila pretraga po imenu prezimenu ili eventualno maticnom broju a ne po id koji je interno u bazi i nigde drugo se ne moze naci

**Comment by Irma12** [comment]
Ako mozes da objasnis kakve veze ima pretraga sa opisom problema?

**Comment by ensarmuratovic** [comment]
Posto je issue vrlo nejasan i nije dovoljno opisan ja cu ga zatvoriti.
