### ISSUE TITLE
Forma se ne prilagodi maximizaciji

### ISSUE THREAD

**Issue by nihad92** [SoftverInzenjeringETFSA/SI2014Tim11#77]
Komponenta:
Izmjena obracuna

commit ID:
e3313c2

Opis problema:
Forma ne rasporedjuje svoje komponente u odnosu na promenu velicini windowa

Koraci za reproduciranje problema:
1. ulogovati se kao operater sa privilegijama
2. odabrati opciju obracuni 
3. odabrati uposlenika
4. kliknuti izmjena obracuna
5. maksimizirati window

Dobijeni rezultat:
![prilagodi](https://cloud.githubusercontent.com/assets/11067294/7899339/b194e490-071f-11e5-8538-191f0ea58dad.PNG)

forma se ne rasiri ostane u originalnoj velicini vezana za top i left margine

isto se desava i na drugim formama

**Comment by Irma12** [comment]
Ne vidim da to utice na funkcionalnosti, nigdje nije navedeno da ce biti prilagođeno maximizaciji.
